version: "3"

services:
  planqdnode0:
    container_name: planqdnode0
    image: "planqd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-planqd.log}
    volumes:
      - ./localnet-setup/node0/planqd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  planqdnode1:
    container_name: planqdnode1
    image: "planqd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-planqd.log}
    volumes:
      - ./localnet-setup/node1/planqd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  planqdnode2:
    container_name: planqdnode2
    image: "planqd/node"
    environment:
      - ID=2
      - LOG=${LOG:-planqd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/planqd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  planqdnode3:
    container_name: planqdnode3
    image: "planqd/node"
    environment:
      - ID=3
      - LOG=${LOG:-planqd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/planqd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
